// Form Personal Training — exercise catalog (v2)
// Single source of truth for the app's exercise library and plan builder.
// Generated file. 84 exercises. Keep slugs (id) stable: they are
// referenced by Supabase rows (plan_day_exercises.exercise_id, workout_sets.exercise_id).

export const MUSCLE_GROUPS = [
  "Chest", "Back", "Shoulders", "Biceps", "Triceps", "Quads", "Hamstrings", "Glutes", "Calves", "Core", "Forearms", "Full Body",
];

export const EQUIPMENT_TYPES = [
  "barbell", "dumbbell", "machine", "cable", "bodyweight", "kettlebell", "band", "plate",
];

export const exercises = [
  { id: "barbell-bench-press", name: "Barbell Bench Press", primary_muscle: "Chest", category: "push", equipment: "barbell", movement_pattern: "horizontal_push", is_compound: true },
  { id: "incline-barbell-press", name: "Incline Barbell Press", primary_muscle: "Chest", category: "push", equipment: "barbell", movement_pattern: "horizontal_push", is_compound: true },
  { id: "dumbbell-bench-press", name: "Dumbbell Bench Press", primary_muscle: "Chest", category: "push", equipment: "dumbbell", movement_pattern: "horizontal_push", is_compound: true },
  { id: "incline-dumbbell-press", name: "Incline Dumbbell Press", primary_muscle: "Chest", category: "push", equipment: "dumbbell", movement_pattern: "horizontal_push", is_compound: true },
  { id: "machine-chest-press", name: "Machine Chest Press", primary_muscle: "Chest", category: "push", equipment: "machine", movement_pattern: "horizontal_push", is_compound: true },
  { id: "pec-deck", name: "Pec Deck Fly", primary_muscle: "Chest", category: "push", equipment: "machine", movement_pattern: "isolation", is_compound: false },
  { id: "cable-fly", name: "Cable Fly", primary_muscle: "Chest", category: "push", equipment: "cable", movement_pattern: "isolation", is_compound: false },
  { id: "dumbbell-fly", name: "Dumbbell Fly", primary_muscle: "Chest", category: "push", equipment: "dumbbell", movement_pattern: "isolation", is_compound: false },
  { id: "push-up", name: "Push-Up", primary_muscle: "Chest", category: "push", equipment: "bodyweight", movement_pattern: "horizontal_push", is_compound: true },
  { id: "chest-dip", name: "Chest Dip", primary_muscle: "Chest", category: "push", equipment: "bodyweight", movement_pattern: "horizontal_push", is_compound: true },
  { id: "deadlift", name: "Conventional Deadlift", primary_muscle: "Back", category: "pull", equipment: "barbell", movement_pattern: "hinge", is_compound: true },
  { id: "barbell-row", name: "Barbell Bent-Over Row", primary_muscle: "Back", category: "pull", equipment: "barbell", movement_pattern: "horizontal_pull", is_compound: true },
  { id: "pendlay-row", name: "Pendlay Row", primary_muscle: "Back", category: "pull", equipment: "barbell", movement_pattern: "horizontal_pull", is_compound: true },
  { id: "dumbbell-row", name: "One-Arm Dumbbell Row", primary_muscle: "Back", category: "pull", equipment: "dumbbell", movement_pattern: "horizontal_pull", is_compound: true },
  { id: "pull-up", name: "Pull-Up", primary_muscle: "Back", category: "pull", equipment: "bodyweight", movement_pattern: "vertical_pull", is_compound: true },
  { id: "chin-up", name: "Chin-Up", primary_muscle: "Back", category: "pull", equipment: "bodyweight", movement_pattern: "vertical_pull", is_compound: true },
  { id: "lat-pulldown", name: "Lat Pulldown", primary_muscle: "Back", category: "pull", equipment: "cable", movement_pattern: "vertical_pull", is_compound: true },
  { id: "seated-cable-row", name: "Seated Cable Row", primary_muscle: "Back", category: "pull", equipment: "cable", movement_pattern: "horizontal_pull", is_compound: true },
  { id: "machine-row", name: "Machine Row", primary_muscle: "Back", category: "pull", equipment: "machine", movement_pattern: "horizontal_pull", is_compound: true },
  { id: "straight-arm-pulldown", name: "Straight-Arm Pulldown", primary_muscle: "Back", category: "pull", equipment: "cable", movement_pattern: "isolation", is_compound: false },
  { id: "face-pull", name: "Face Pull", primary_muscle: "Back", category: "pull", equipment: "cable", movement_pattern: "isolation", is_compound: false },
  { id: "t-bar-row", name: "T-Bar Row", primary_muscle: "Back", category: "pull", equipment: "barbell", movement_pattern: "horizontal_pull", is_compound: true },
  { id: "overhead-press", name: "Barbell Overhead Press", primary_muscle: "Shoulders", category: "push", equipment: "barbell", movement_pattern: "vertical_push", is_compound: true },
  { id: "dumbbell-shoulder-press", name: "Dumbbell Shoulder Press", primary_muscle: "Shoulders", category: "push", equipment: "dumbbell", movement_pattern: "vertical_push", is_compound: true },
  { id: "machine-shoulder-press", name: "Machine Shoulder Press", primary_muscle: "Shoulders", category: "push", equipment: "machine", movement_pattern: "vertical_push", is_compound: true },
  { id: "lateral-raise", name: "Dumbbell Lateral Raise", primary_muscle: "Shoulders", category: "push", equipment: "dumbbell", movement_pattern: "isolation", is_compound: false },
  { id: "cable-lateral-raise", name: "Cable Lateral Raise", primary_muscle: "Shoulders", category: "push", equipment: "cable", movement_pattern: "isolation", is_compound: false },
  { id: "rear-delt-fly", name: "Rear Delt Fly", primary_muscle: "Shoulders", category: "pull", equipment: "dumbbell", movement_pattern: "isolation", is_compound: false },
  { id: "arnold-press", name: "Arnold Press", primary_muscle: "Shoulders", category: "push", equipment: "dumbbell", movement_pattern: "vertical_push", is_compound: true },
  { id: "front-raise", name: "Front Raise", primary_muscle: "Shoulders", category: "push", equipment: "dumbbell", movement_pattern: "isolation", is_compound: false },
  { id: "upright-row", name: "Upright Row", primary_muscle: "Shoulders", category: "pull", equipment: "barbell", movement_pattern: "isolation", is_compound: false },
  { id: "barbell-curl", name: "Barbell Curl", primary_muscle: "Biceps", category: "pull", equipment: "barbell", movement_pattern: "isolation", is_compound: false },
  { id: "dumbbell-curl", name: "Dumbbell Curl", primary_muscle: "Biceps", category: "pull", equipment: "dumbbell", movement_pattern: "isolation", is_compound: false },
  { id: "incline-dumbbell-curl", name: "Incline Dumbbell Curl", primary_muscle: "Biceps", category: "pull", equipment: "dumbbell", movement_pattern: "isolation", is_compound: false },
  { id: "hammer-curl", name: "Hammer Curl", primary_muscle: "Biceps", category: "pull", equipment: "dumbbell", movement_pattern: "isolation", is_compound: false },
  { id: "preacher-curl", name: "Preacher Curl", primary_muscle: "Biceps", category: "pull", equipment: "machine", movement_pattern: "isolation", is_compound: false },
  { id: "cable-curl", name: "Cable Curl", primary_muscle: "Biceps", category: "pull", equipment: "cable", movement_pattern: "isolation", is_compound: false },
  { id: "ez-bar-curl", name: "EZ-Bar Curl", primary_muscle: "Biceps", category: "pull", equipment: "barbell", movement_pattern: "isolation", is_compound: false },
  { id: "close-grip-bench", name: "Close-Grip Bench Press", primary_muscle: "Triceps", category: "push", equipment: "barbell", movement_pattern: "horizontal_push", is_compound: true },
  { id: "triceps-pushdown", name: "Triceps Pushdown", primary_muscle: "Triceps", category: "push", equipment: "cable", movement_pattern: "isolation", is_compound: false },
  { id: "overhead-triceps-ext", name: "Overhead Triceps Extension", primary_muscle: "Triceps", category: "push", equipment: "dumbbell", movement_pattern: "isolation", is_compound: false },
  { id: "skullcrusher", name: "Lying Triceps Extension (Skullcrusher)", primary_muscle: "Triceps", category: "push", equipment: "barbell", movement_pattern: "isolation", is_compound: false },
  { id: "triceps-dip", name: "Triceps Dip", primary_muscle: "Triceps", category: "push", equipment: "bodyweight", movement_pattern: "vertical_push", is_compound: true },
  { id: "rope-pushdown", name: "Rope Pushdown", primary_muscle: "Triceps", category: "push", equipment: "cable", movement_pattern: "isolation", is_compound: false },
  { id: "kickback", name: "Triceps Kickback", primary_muscle: "Triceps", category: "push", equipment: "dumbbell", movement_pattern: "isolation", is_compound: false },
  { id: "back-squat", name: "Barbell Back Squat", primary_muscle: "Quads", category: "legs", equipment: "barbell", movement_pattern: "squat", is_compound: true },
  { id: "front-squat", name: "Front Squat", primary_muscle: "Quads", category: "legs", equipment: "barbell", movement_pattern: "squat", is_compound: true },
  { id: "leg-press", name: "Leg Press", primary_muscle: "Quads", category: "legs", equipment: "machine", movement_pattern: "squat", is_compound: true },
  { id: "hack-squat", name: "Hack Squat", primary_muscle: "Quads", category: "legs", equipment: "machine", movement_pattern: "squat", is_compound: true },
  { id: "goblet-squat", name: "Goblet Squat", primary_muscle: "Quads", category: "legs", equipment: "dumbbell", movement_pattern: "squat", is_compound: true },
  { id: "leg-extension", name: "Leg Extension", primary_muscle: "Quads", category: "legs", equipment: "machine", movement_pattern: "isolation", is_compound: false },
  { id: "walking-lunge", name: "Walking Lunge", primary_muscle: "Quads", category: "legs", equipment: "dumbbell", movement_pattern: "lunge", is_compound: true },
  { id: "bulgarian-split-squat", name: "Bulgarian Split Squat", primary_muscle: "Quads", category: "legs", equipment: "dumbbell", movement_pattern: "lunge", is_compound: true },
  { id: "bodyweight-squat", name: "Bodyweight Squat", primary_muscle: "Quads", category: "legs", equipment: "bodyweight", movement_pattern: "squat", is_compound: true },
  { id: "romanian-deadlift", name: "Romanian Deadlift", primary_muscle: "Hamstrings", category: "legs", equipment: "barbell", movement_pattern: "hinge", is_compound: true },
  { id: "stiff-leg-deadlift", name: "Stiff-Leg Deadlift", primary_muscle: "Hamstrings", category: "legs", equipment: "barbell", movement_pattern: "hinge", is_compound: true },
  { id: "lying-leg-curl", name: "Lying Leg Curl", primary_muscle: "Hamstrings", category: "legs", equipment: "machine", movement_pattern: "isolation", is_compound: false },
  { id: "seated-leg-curl", name: "Seated Leg Curl", primary_muscle: "Hamstrings", category: "legs", equipment: "machine", movement_pattern: "isolation", is_compound: false },
  { id: "nordic-curl", name: "Nordic Hamstring Curl", primary_muscle: "Hamstrings", category: "legs", equipment: "bodyweight", movement_pattern: "isolation", is_compound: false },
  { id: "good-morning", name: "Good Morning", primary_muscle: "Hamstrings", category: "legs", equipment: "barbell", movement_pattern: "hinge", is_compound: true },
  { id: "db-romanian-deadlift", name: "Dumbbell Romanian Deadlift", primary_muscle: "Hamstrings", category: "legs", equipment: "dumbbell", movement_pattern: "hinge", is_compound: true },
  { id: "hip-thrust", name: "Barbell Hip Thrust", primary_muscle: "Glutes", category: "legs", equipment: "barbell", movement_pattern: "hinge", is_compound: true },
  { id: "glute-bridge", name: "Glute Bridge", primary_muscle: "Glutes", category: "legs", equipment: "bodyweight", movement_pattern: "hinge", is_compound: true },
  { id: "cable-kickback", name: "Cable Glute Kickback", primary_muscle: "Glutes", category: "legs", equipment: "cable", movement_pattern: "isolation", is_compound: false },
  { id: "sumo-deadlift", name: "Sumo Deadlift", primary_muscle: "Glutes", category: "legs", equipment: "barbell", movement_pattern: "hinge", is_compound: true },
  { id: "step-up", name: "Step-Up", primary_muscle: "Glutes", category: "legs", equipment: "dumbbell", movement_pattern: "lunge", is_compound: true },
  { id: "abduction-machine", name: "Hip Abduction Machine", primary_muscle: "Glutes", category: "legs", equipment: "machine", movement_pattern: "isolation", is_compound: false },
  { id: "standing-calf-raise", name: "Standing Calf Raise", primary_muscle: "Calves", category: "legs", equipment: "machine", movement_pattern: "isolation", is_compound: false },
  { id: "seated-calf-raise", name: "Seated Calf Raise", primary_muscle: "Calves", category: "legs", equipment: "machine", movement_pattern: "isolation", is_compound: false },
  { id: "db-calf-raise", name: "Dumbbell Calf Raise", primary_muscle: "Calves", category: "legs", equipment: "dumbbell", movement_pattern: "isolation", is_compound: false },
  { id: "leg-press-calf-raise", name: "Leg Press Calf Raise", primary_muscle: "Calves", category: "legs", equipment: "machine", movement_pattern: "isolation", is_compound: false },
  { id: "plank", name: "Plank", primary_muscle: "Core", category: "core", equipment: "bodyweight", movement_pattern: "core", is_compound: false },
  { id: "hanging-leg-raise", name: "Hanging Leg Raise", primary_muscle: "Core", category: "core", equipment: "bodyweight", movement_pattern: "core", is_compound: false },
  { id: "cable-crunch", name: "Cable Crunch", primary_muscle: "Core", category: "core", equipment: "cable", movement_pattern: "core", is_compound: false },
  { id: "crunch", name: "Crunch", primary_muscle: "Core", category: "core", equipment: "bodyweight", movement_pattern: "core", is_compound: false },
  { id: "russian-twist", name: "Russian Twist", primary_muscle: "Core", category: "core", equipment: "bodyweight", movement_pattern: "core", is_compound: false },
  { id: "ab-wheel", name: "Ab Wheel Rollout", primary_muscle: "Core", category: "core", equipment: "bodyweight", movement_pattern: "core", is_compound: false },
  { id: "dead-bug", name: "Dead Bug", primary_muscle: "Core", category: "core", equipment: "bodyweight", movement_pattern: "core", is_compound: false },
  { id: "wrist-curl", name: "Wrist Curl", primary_muscle: "Forearms", category: "pull", equipment: "dumbbell", movement_pattern: "isolation", is_compound: false },
  { id: "farmers-carry", name: "Farmer's Carry", primary_muscle: "Forearms", category: "full_body", equipment: "dumbbell", movement_pattern: "carry", is_compound: true },
  { id: "kettlebell-swing", name: "Kettlebell Swing", primary_muscle: "Full Body", category: "full_body", equipment: "kettlebell", movement_pattern: "hinge", is_compound: true },
  { id: "clean-and-press", name: "Clean and Press", primary_muscle: "Full Body", category: "full_body", equipment: "barbell", movement_pattern: "vertical_push", is_compound: true },
  { id: "band-pull-apart", name: "Band Pull-Apart", primary_muscle: "Shoulders", category: "pull", equipment: "band", movement_pattern: "isolation", is_compound: false },
  { id: "trap-bar-deadlift", name: "Trap Bar Deadlift", primary_muscle: "Full Body", category: "legs", equipment: "plate", movement_pattern: "hinge", is_compound: true },
];

export const exercisesById = Object.fromEntries(exercises.map((e) => [e.id, e]));
