-- Form Personal Training v2 — exercise catalog seed
-- Run AFTER schema.sql. Populates the shared, read-only exercises table.
-- 84 rows. Idempotent: re-running updates existing rows by id.

insert into public.exercises (id, name, primary_muscle, category, equipment, movement_pattern, is_compound) values
  ('barbell-bench-press', 'Barbell Bench Press', 'Chest', 'push', 'barbell', 'horizontal_push', true),
  ('incline-barbell-press', 'Incline Barbell Press', 'Chest', 'push', 'barbell', 'horizontal_push', true),
  ('dumbbell-bench-press', 'Dumbbell Bench Press', 'Chest', 'push', 'dumbbell', 'horizontal_push', true),
  ('incline-dumbbell-press', 'Incline Dumbbell Press', 'Chest', 'push', 'dumbbell', 'horizontal_push', true),
  ('machine-chest-press', 'Machine Chest Press', 'Chest', 'push', 'machine', 'horizontal_push', true),
  ('pec-deck', 'Pec Deck Fly', 'Chest', 'push', 'machine', 'isolation', false),
  ('cable-fly', 'Cable Fly', 'Chest', 'push', 'cable', 'isolation', false),
  ('dumbbell-fly', 'Dumbbell Fly', 'Chest', 'push', 'dumbbell', 'isolation', false),
  ('push-up', 'Push-Up', 'Chest', 'push', 'bodyweight', 'horizontal_push', true),
  ('chest-dip', 'Chest Dip', 'Chest', 'push', 'bodyweight', 'horizontal_push', true),
  ('deadlift', 'Conventional Deadlift', 'Back', 'pull', 'barbell', 'hinge', true),
  ('barbell-row', 'Barbell Bent-Over Row', 'Back', 'pull', 'barbell', 'horizontal_pull', true),
  ('pendlay-row', 'Pendlay Row', 'Back', 'pull', 'barbell', 'horizontal_pull', true),
  ('dumbbell-row', 'One-Arm Dumbbell Row', 'Back', 'pull', 'dumbbell', 'horizontal_pull', true),
  ('pull-up', 'Pull-Up', 'Back', 'pull', 'bodyweight', 'vertical_pull', true),
  ('chin-up', 'Chin-Up', 'Back', 'pull', 'bodyweight', 'vertical_pull', true),
  ('lat-pulldown', 'Lat Pulldown', 'Back', 'pull', 'cable', 'vertical_pull', true),
  ('seated-cable-row', 'Seated Cable Row', 'Back', 'pull', 'cable', 'horizontal_pull', true),
  ('machine-row', 'Machine Row', 'Back', 'pull', 'machine', 'horizontal_pull', true),
  ('straight-arm-pulldown', 'Straight-Arm Pulldown', 'Back', 'pull', 'cable', 'isolation', false),
  ('face-pull', 'Face Pull', 'Back', 'pull', 'cable', 'isolation', false),
  ('t-bar-row', 'T-Bar Row', 'Back', 'pull', 'barbell', 'horizontal_pull', true),
  ('overhead-press', 'Barbell Overhead Press', 'Shoulders', 'push', 'barbell', 'vertical_push', true),
  ('dumbbell-shoulder-press', 'Dumbbell Shoulder Press', 'Shoulders', 'push', 'dumbbell', 'vertical_push', true),
  ('machine-shoulder-press', 'Machine Shoulder Press', 'Shoulders', 'push', 'machine', 'vertical_push', true),
  ('lateral-raise', 'Dumbbell Lateral Raise', 'Shoulders', 'push', 'dumbbell', 'isolation', false),
  ('cable-lateral-raise', 'Cable Lateral Raise', 'Shoulders', 'push', 'cable', 'isolation', false),
  ('rear-delt-fly', 'Rear Delt Fly', 'Shoulders', 'pull', 'dumbbell', 'isolation', false),
  ('arnold-press', 'Arnold Press', 'Shoulders', 'push', 'dumbbell', 'vertical_push', true),
  ('front-raise', 'Front Raise', 'Shoulders', 'push', 'dumbbell', 'isolation', false),
  ('upright-row', 'Upright Row', 'Shoulders', 'pull', 'barbell', 'isolation', false),
  ('barbell-curl', 'Barbell Curl', 'Biceps', 'pull', 'barbell', 'isolation', false),
  ('dumbbell-curl', 'Dumbbell Curl', 'Biceps', 'pull', 'dumbbell', 'isolation', false),
  ('incline-dumbbell-curl', 'Incline Dumbbell Curl', 'Biceps', 'pull', 'dumbbell', 'isolation', false),
  ('hammer-curl', 'Hammer Curl', 'Biceps', 'pull', 'dumbbell', 'isolation', false),
  ('preacher-curl', 'Preacher Curl', 'Biceps', 'pull', 'machine', 'isolation', false),
  ('cable-curl', 'Cable Curl', 'Biceps', 'pull', 'cable', 'isolation', false),
  ('ez-bar-curl', 'EZ-Bar Curl', 'Biceps', 'pull', 'barbell', 'isolation', false),
  ('close-grip-bench', 'Close-Grip Bench Press', 'Triceps', 'push', 'barbell', 'horizontal_push', true),
  ('triceps-pushdown', 'Triceps Pushdown', 'Triceps', 'push', 'cable', 'isolation', false),
  ('overhead-triceps-ext', 'Overhead Triceps Extension', 'Triceps', 'push', 'dumbbell', 'isolation', false),
  ('skullcrusher', 'Lying Triceps Extension (Skullcrusher)', 'Triceps', 'push', 'barbell', 'isolation', false),
  ('triceps-dip', 'Triceps Dip', 'Triceps', 'push', 'bodyweight', 'vertical_push', true),
  ('rope-pushdown', 'Rope Pushdown', 'Triceps', 'push', 'cable', 'isolation', false),
  ('kickback', 'Triceps Kickback', 'Triceps', 'push', 'dumbbell', 'isolation', false),
  ('back-squat', 'Barbell Back Squat', 'Quads', 'legs', 'barbell', 'squat', true),
  ('front-squat', 'Front Squat', 'Quads', 'legs', 'barbell', 'squat', true),
  ('leg-press', 'Leg Press', 'Quads', 'legs', 'machine', 'squat', true),
  ('hack-squat', 'Hack Squat', 'Quads', 'legs', 'machine', 'squat', true),
  ('goblet-squat', 'Goblet Squat', 'Quads', 'legs', 'dumbbell', 'squat', true),
  ('leg-extension', 'Leg Extension', 'Quads', 'legs', 'machine', 'isolation', false),
  ('walking-lunge', 'Walking Lunge', 'Quads', 'legs', 'dumbbell', 'lunge', true),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', 'Quads', 'legs', 'dumbbell', 'lunge', true),
  ('bodyweight-squat', 'Bodyweight Squat', 'Quads', 'legs', 'bodyweight', 'squat', true),
  ('romanian-deadlift', 'Romanian Deadlift', 'Hamstrings', 'legs', 'barbell', 'hinge', true),
  ('stiff-leg-deadlift', 'Stiff-Leg Deadlift', 'Hamstrings', 'legs', 'barbell', 'hinge', true),
  ('lying-leg-curl', 'Lying Leg Curl', 'Hamstrings', 'legs', 'machine', 'isolation', false),
  ('seated-leg-curl', 'Seated Leg Curl', 'Hamstrings', 'legs', 'machine', 'isolation', false),
  ('nordic-curl', 'Nordic Hamstring Curl', 'Hamstrings', 'legs', 'bodyweight', 'isolation', false),
  ('good-morning', 'Good Morning', 'Hamstrings', 'legs', 'barbell', 'hinge', true),
  ('db-romanian-deadlift', 'Dumbbell Romanian Deadlift', 'Hamstrings', 'legs', 'dumbbell', 'hinge', true),
  ('hip-thrust', 'Barbell Hip Thrust', 'Glutes', 'legs', 'barbell', 'hinge', true),
  ('glute-bridge', 'Glute Bridge', 'Glutes', 'legs', 'bodyweight', 'hinge', true),
  ('cable-kickback', 'Cable Glute Kickback', 'Glutes', 'legs', 'cable', 'isolation', false),
  ('sumo-deadlift', 'Sumo Deadlift', 'Glutes', 'legs', 'barbell', 'hinge', true),
  ('step-up', 'Step-Up', 'Glutes', 'legs', 'dumbbell', 'lunge', true),
  ('abduction-machine', 'Hip Abduction Machine', 'Glutes', 'legs', 'machine', 'isolation', false),
  ('standing-calf-raise', 'Standing Calf Raise', 'Calves', 'legs', 'machine', 'isolation', false),
  ('seated-calf-raise', 'Seated Calf Raise', 'Calves', 'legs', 'machine', 'isolation', false),
  ('db-calf-raise', 'Dumbbell Calf Raise', 'Calves', 'legs', 'dumbbell', 'isolation', false),
  ('leg-press-calf-raise', 'Leg Press Calf Raise', 'Calves', 'legs', 'machine', 'isolation', false),
  ('plank', 'Plank', 'Core', 'core', 'bodyweight', 'core', false),
  ('hanging-leg-raise', 'Hanging Leg Raise', 'Core', 'core', 'bodyweight', 'core', false),
  ('cable-crunch', 'Cable Crunch', 'Core', 'core', 'cable', 'core', false),
  ('crunch', 'Crunch', 'Core', 'core', 'bodyweight', 'core', false),
  ('russian-twist', 'Russian Twist', 'Core', 'core', 'bodyweight', 'core', false),
  ('ab-wheel', 'Ab Wheel Rollout', 'Core', 'core', 'bodyweight', 'core', false),
  ('dead-bug', 'Dead Bug', 'Core', 'core', 'bodyweight', 'core', false),
  ('wrist-curl', 'Wrist Curl', 'Forearms', 'pull', 'dumbbell', 'isolation', false),
  ('farmers-carry', 'Farmer''s Carry', 'Forearms', 'full_body', 'dumbbell', 'carry', true),
  ('kettlebell-swing', 'Kettlebell Swing', 'Full Body', 'full_body', 'kettlebell', 'hinge', true),
  ('clean-and-press', 'Clean and Press', 'Full Body', 'full_body', 'barbell', 'vertical_push', true),
  ('band-pull-apart', 'Band Pull-Apart', 'Shoulders', 'pull', 'band', 'isolation', false),
  ('trap-bar-deadlift', 'Trap Bar Deadlift', 'Full Body', 'legs', 'plate', 'hinge', true)
on conflict (id) do update set
  name = excluded.name,
  primary_muscle = excluded.primary_muscle,
  category = excluded.category,
  equipment = excluded.equipment,
  movement_pattern = excluded.movement_pattern,
  is_compound = excluded.is_compound;
